# Generated by Django 4.2.6 on 2023-10-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0002_rename_member_goods"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goods",
            old_name="firstname",
            new_name="goodsname",
        ),
        migrations.RemoveField(
            model_name="goods",
            name="lastname",
        ),
        migrations.AddField(
            model_name="goods",
            name="description",
            field=models.CharField(max_length=2200, null=True),
        ),
        migrations.AddField(
            model_name="goods",
            name="price",
            field=models.FloatField(null=True),
        ),
    ]
