# Generated by Django 4.2.6 on 2023-10-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0004_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
