# Generated by Django 4.2.6 on 2023-10-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0005_cart_price_alter_cart_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
