# Generated by Django 4.2.6 on 2023-10-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0006_alter_cart_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="sum_price",
            field=models.FloatField(default=0),
        ),
    ]
