# Generated by Django 4.2.6 on 2023-10-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0007_cart_sum_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="sum_price",
            field=models.FloatField(default=1),
        ),
    ]
