# Generated by Django 4.2.6 on 2023-10-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0008_alter_cart_sum_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="sum_price",
            field=models.FloatField(null=True),
        ),
    ]
