# Generated by Django 4.2.6 on 2023-10-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0010_remove_cart_product_cart_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="product_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
