# Generated by Django 4.2.6 on 2023-10-27 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goods", "0011_cart_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ordered",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(null=True)),
                ("product_name", models.CharField(max_length=255, null=True)),
                ("price", models.FloatField(null=True)),
                ("quantity", models.IntegerField(null=True)),
                ("sum_price", models.FloatField(null=True)),
                ("firstname", models.CharField(max_length=255, null=True)),
                ("lastname", models.CharField(max_length=255, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                ("paid", models.BooleanField(default=True)),
                ("datetime", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
