# Generated by Django 4.2.6 on 2023-10-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0012_ordered"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordered",
            name="tel",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
