# Generated by Django 4.2.6 on 2023-10-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0013_ordered_tel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(null=True)),
                ("product_name", models.CharField(max_length=255, null=True)),
                ("price", models.FloatField(null=True)),
                ("quantity", models.IntegerField(null=True)),
                ("sum_price", models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="ordered",
            name="price",
        ),
        migrations.RemoveField(
            model_name="ordered",
            name="product_id",
        ),
        migrations.RemoveField(
            model_name="ordered",
            name="product_name",
        ),
        migrations.RemoveField(
            model_name="ordered",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="ordered",
            name="sum_price",
        ),
        migrations.AddField(
            model_name="ordered",
            name="products",
            field=models.ManyToManyField(to="goods.product"),
        ),
    ]
