# Generated by Django 4.2.6 on 2023-10-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0015_alter_ordered_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordered",
            name="total_price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="ordered",
            name="firstname",
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name="ordered",
            name="lastname",
            field=models.CharField(max_length=31, null=True),
        ),
    ]
