# Generated by Django 4.2.6 on 2023-10-28 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0016_ordered_total_price_alter_ordered_firstname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, storage="img", upload_to="image"
            ),
            preserve_default=False,
        ),
    ]
